### ISSUE TITLE
There is an error in the download URL of the system.json file

### ISSUE THREAD

**Issue by nerdroom** [DiceT/starforged#8]
I was unable to download this via Foundry or by putting the direct URL to the system.json file. It would give me errors on not finding the zip file.

So I created a fork and found that you need to set the zip file name to "v.0.8.0.zip" rather than "v0.8.0.zip"

Once I did that, I was able to download it correctly.

**Comment by DiceT** [comment]
Fixed: Update should work in Foundry with the new version.
https://raw.githubusercontent.com/dicet/starforged/0.8.1/system.json
